[package]
name = "awesome-service"
version = "1.0.0"
authors = ["Example Person <example@person.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
