[tool.pylint."MESSAGES CONTROL"]

# Disable the message, report, category or checker with the given id(s). You
# can either give multiple identifiers separated by comma (,) or put this
# option multiple times (only on the command line, not in the configuration
# file where it should appear only once). You can also use "--disable=all" to
# disable everything first and then reenable specific checks. For example, if
# you want to run only the similarities checker, you can use "--disable=all
# --enable=similarities". If you want to run only the classes checker, but have
# no Warning level messages displayed, use "--disable=all --enable=classes
# --disable=W".
disable=[
        "no-member",
        "fixme",
        "print-statement",
        "parameter-unpacking",
        "unpacking-in-except",
        "old-raise-syntax",
        "backtick",
        "long-suffix",
        "old-ne-operator",
        "old-octal-literal",
        "import-star-module-level",
        "non-ascii-bytes-literal",
        "apply-builtin",
        "basestring-builtin",
        "buffer-builtin",
        "cmp-builtin",
        "coerce-builtin",
        "execfile-builtin",
        "file-builtin",
        "long-builtin",
        "raw_input-builtin",
        "reduce-builtin",
        "standarderror-builtin",
        "unicode-builtin",
        "xrange-builtin",
        "coerce-method",
        "delslice-method",
        "getslice-method",
        "setslice-method",
        "no-absolute-import",
        "old-division",
        "dict-iter-method",
        "dict-view-method",
        "next-method-called",
        "metaclass-assignment",
        "indexing-exception",
        "raising-string",
        "reload-builtin",
        "oct-method",
        "hex-method",
        "nonzero-method",
        "cmp-method",
        "input-builtin",
        "round-builtin",
        "intern-builtin",
        "unichr-builtin",
        "map-builtin-not-iterating",
        "zip-builtin-not-iterating",
        "range-builtin-not-iterating",
        "filter-builtin-not-iterating",
        "using-cmp-argument",
        "eq-without-hash",
        "div-method",
        "idiv-method",
        "rdiv-method",
        "exception-message-attribute",
        "invalid-str-codec",
        "sys-max-int",
        "bad-python3-import",
        "deprecated-string-function",
        "deprecated-str-translate-call",
        "deprecated-itertools-function",
        "deprecated-types-field",
        "next-method-defined",
        "dict-items-not-iterating",
        "dict-keys-not-iterating",
        "dict-values-not-iterating",
        "deprecated-operator-function",
        "deprecated-urllib-function",
        "xreadlines-attribute",
        "deprecated-sys-function",
        "exception-escape",
        "comprehension-escape",
        "C0330"]

[tool.pylint.SIMILARITIES]
# Ignore imports when computing similarities.
ignore-imports=true

# Minimum lines number of a similarity.
min-similarity-lines=16
