[package]
name = "@packageName@"
version = "@version@"
authors = ["Goodbye Kansas Pipeline team <pipeline@goodbyekansas.com>"]
edition = "2018"

[dependencies]
bytes = "1"
prost = "0.7"
tempfile = "3"
@includeTonic@
@external@
