#! @bash@
# shellcheck shell=bash

@preamble@

set -uo pipefail
if [ $# -eq 0 ]; then
    if [ -z "${NEDRYLAND_CHECK_FILES:-}" ]; then
        @nixLinter@ check .
        exit $?
    else
        exitCode=0
        # statix cannot support multiple files
        # https://github.com/nerdypepper/statix/issues/69
        while mapfile -t -n 1 nix_files && ((${#nix_files[@]})); do
            if ! @nixLinter@ check "${nix_files[@]}"; then
                exitCode=1;
            fi
        done <<< "$(grep ".nix$" < "$NEDRYLAND_CHECK_FILES")"
        exit $exitCode;
    fi
else
    @nixLinter@ "$@"
fi
