name: 🌱 Setup nix
description: Setup nix with ssh agent and optionally config
inputs:
  access-key:
    description: SSH key to use for accessing repositories through nix.
    required: false

  builders-access-key:
    description: SSH key to use for accessing builders, defaults to the same used for repositories.
    required: false

  builders:
    description: SSH connection string for nix builders.
    type: string
    required: false

  config-path:
    description: Path to a nix configuration file.
    required: false

  version:
    description: Nix version to install.
    type: string
    default: 2.11.1

  cachix-name:
    description: The name of the cachix cache to use.
    type: string
    required: false

  cachix-signing-key:
    description: The cachix signing key.
    type: string
    required: false

  cachix-auth-token:
    description: The cachix auth token.
    type: string
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v20
      with:
        install_url: https://releases.nixos.org/nix/nix-${{ inputs.version }}/install

    - name: Create Nix configuration
      run: |
        mkdir -p ~/.config/nix

        if [ -f "${{ inputs.config-path }}" ]; then
          cp ${{ inputs.config-path }} ~/.config/nix/nix.conf
        fi

        if ! grep "access-tokens" ~/.config/nix/nix.conf; then
          echo "access-tokens = github.com=${{ github.token }}" >> ~/.config/nix/nix.conf
        fi
      shell: sh

    - name: Setup SSH
      if: ${{ inputs.access-key != '' }}
      env:
        CI_ACCESS_KEY: ${{ inputs.access-key }}
        BUILDERS_ACCESS_KEY: ${{ inputs.builders-access-key || inputs.access-key }}
        SSH_CONFIG: ${{ github.action_path }}/ssh-conf
      run: ${{ github.action_path }}/ssh-agent.sh
      shell: sh

    - name: Set up nix builders ssh connection
      env:
        BUILD_HOST: ${{ inputs.builders }}
      if: ${{ inputs.builders != '' && inputs.access-key != '' }}
      run: |
        build_host="${BUILD_HOST##*@}"
        # Add host key to root (for connections made by the nix-daemon)
        echo "::group::Test nix-daemon SSH"
        sudo -i ssh-keyscan -t ed25519 "$build_host" | sudo tee /root/.ssh/known_hosts
        sudo ls /root/.ssh
        sudo -i nix store ping --store "ssh://$BUILD_HOST"
        echo "nix-daemon connection successful"
        echo "::endgroup::"

        # Add host key to user (for connections made by the nix client)
        echo "::group::Test nix client SSH"
        ssh-keyscan -t ed25519 "$build_host" >>~/.ssh/known_hosts
        nix store ping --store ssh://"$BUILD_HOST"
        echo "nix client connection successful"
        echo "::endgroup::"
      shell: bash


    - name: Setup Cachix
      if: ${{ inputs.cachix-name != '' }}
      uses: cachix/cachix-action@v12
      with:
        name: ${{ inputs.cachix-name }}
        signingKey: ${{ inputs.cachix-signing-key }}
        authToken: ${{ inputs.cachix-auth-token }}
