createCargoConfig() {
  if [ -n "$cargoConfigs" ]; then

    markerComment="# generated by nedryland"

    if [ -f .cargo/config.toml ] && [ "$(head -n 1 .cargo/config.toml)" != "$markerComment" ]; then
      echo "ERROR: .cargo/config.toml exists and is not created by nedryland"
      echo "This is not currently supported and we need to write the file for"
      echo "internal dependencies to work. Please remove it and add to .gitignore"
      exit 1
    fi

    rm -f .cargo/config.toml

    mkdir -p .cargo
    echo "$markerComment" > .cargo/config.toml
    for part in $cargoConfigs; do
      echo "🚜 appending $part to Cargo vendor config"

      echo "" >> .cargo/config.toml
      echo "# from $part" >> .cargo/config.toml
      cat $part >> .cargo/config.toml
    done
    echo "🚜 created Cargo vendor config .cargo/config.toml"
  fi
}


export cargoConfigs+=" @out@/cargo.config.toml"
