[package]
name = "rust-protobuf-compiler"
version = "0.1.0"
authors = ["Goodbye Kansas Pipeline team <pipeline@goodbyekansas.com>"]
edition = "2018"

[dependencies]
tonic-build = "0.3"
structopt = "0.3"
