[package]
name = "rust-protobuf-compiler"
version = "1.0.0"
authors = ["Goodbye Kansas Pipeline team <pipeline@goodbyekansas.com>"]
edition = "2018"

[dependencies]
prost-build = "0.9.0"
structopt = "0.3"
tonic-build = "0.6.0"
