[package]
name = "rust-protobuf-compiler"
version = "1.0.0"
authors = ["Goodbye Kansas Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2021"

[dependencies]
prost-build = "0.10.4"
structopt = "0.3"
tonic-build = "0.7"

