name: Examples

on: [push]

concurrency:
  group: '${{ github.ref_name }}-build-examples-linux'
  cancel-in-progress: true

jobs:
  build-examples-linux:
    name: Linux 🐧
    uses: ./.github/workflows/build-examples-shared.yml
    secrets:
      nix-access-key: ${{ secrets.NIXOS_BUILDERS }}
    with:
      build-platform: x86_64-linux

  build-examples-macos:
    name: macOS 🍎
    uses: ./.github/workflows/build-examples-shared.yml
    secrets:
      nix-access-key: ${{ secrets.NIXOS_BUILDERS }}
    with:
      build-platform: x86_64-darwin
