name: Tests

on: [push]

concurrency:
  group: '${{ github.ref_name }}-tests'
  cancel-in-progress: true

jobs:
  lint:
    name: Lints
    uses: ./.github/workflows/checks.yml
    with:
      nix-version: 2.11.1

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup nix
      uses: ./.github/actions/setup-nix
      with:
        access-key: ${{ secrets.NIXOS_BUILDERS }}
        builders: build@nix-builders.goodbyekansas.com
        config-path: ./.github/workflows/setup/nix.conf
        version: 2.11.1

    - name: Run all tests
      run: nix flake check
